MenoryManagement : main.c menu.c  memory_recovery.c  memory_allocation.c  list_node.c  block_node.c 
	gcc main.c menu.c  memory_recovery.c  memory_allocation.c  list_node.c  block_node.c  -o MemoryManagement -I ./include/
clean :
	rm *.o *.gch
