MenoryManagement : main.c menu.c menu.h memory_recovery.c memory_recovery.h memory_allocation.c memory_allocation.h list_node.c list_node.h block_node.c block_node.h
	gcc main.c menu.c menu.h memory_recovery.c memory_recovery.h memory_allocation.c memory_allocation.h list_node.c list_node.h block_node.c block_node.h -o MemoryManagement
clean :
	rm *.o *.gch
